# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa99166b96043e544d8b912a39de51e08ef9a1e6ae3c0b73f4cac53c1fb4469757df0684a0afb43a2a038d74e2b2a72c487fe6740dd5bde0a88d9177d56d8d38

test:
  secret_key_base: 036156039ee5bde1a61fc0db00e4c2a10a9031d57b8d280da0cc13266c0a7807086752afb9f15d7ae2e1d686e41a97ffaac2224969eb545ffbf5f437f72d4242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
